name: build push image
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - ".github/**"
      - "README.md"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to QUAY 
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_SECRET }}

      -
        name: Build and push to QUAY
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: quay.io/${{secrets.QUAY_USER}}/fast-localtime-check:${{ github.sha }}